Repository katorlys/rweb.site, pull requests merged in 2024-05, with the labels that each got.

#4 Update records.json
  records.json
Labels: ⚠️Pending: confirmation

#5 Update records.json
  records.json
Labels: ✅Approved

#7 Update records.json
  records.json
Labels: ⚠️Pending: confirmation

#9 Remove record :/
  records.json
Labels: ✅Deleted
